# Generated by Django 4.2.4 on 2023-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
